### PR TITLE
MetaSound Implementation - Terminal Ambience

### PR DESCRIPTION
**Pull request by Absolution2015**
There's some Github dark magic in this commit that attributes some changes to README.md to me as well as some changes to CaveMart that I haven't consciously done. As far as my noob awareness goes, I hope these are some inconsequential stuff that isn't in any way affecting anything I haven't actually touched.

This pull request exists for two reasons: Making sure I can finally get Github to do my bidding and send my work out to the main unstable branch, and the MetaSound commit. I've written extensively about it in the commit itself, but here's the same text at the 'pull request' level. Going forward I won't be double-typing the same thing twice:

MetaSound Implementation - Terminal Ambience
Implemented the first MetaSound (as far as I could see), which is the upgraded version of UE4's "Sound Cue" for UE5. More details follow, but first:
MetaSound can be found in the Audio folder: "MS_TerminalChime"
The MetaSound was added to the map "Aqua_2" and can be found at the three screens/monitors/terminals in the map.

MetaSounds, as this example will show, are the best thing to use moving forward. Here are some of the advantages:
- Reducing overall game size.
- Allowing for even more in-engine digital signal processing, 'live' mixing etc.
- Creating even more robust sound systems / hierarchies than before.

MS_TerminalChime is a simple example / test to show the usefulness of MetaSounds. The implementation is simple: A loop of a chime I made that plays when nearing aforementioned terminals in maps - an object ambience.

Going into MS_TerminalChime you can see the only two functions are a wave player (basically required) and a random(f). The random is where the magic happens.

I have randomized the pitch of the sound file to a range of 6 semitones 'surrounding' the original. Every time someone enters the attenuation volume of the MetaSound, the sound file will be played at a different pitch. If you want to see it work more clearly, increase the min/max pitch range in the MetaSound flow graph and give it a spin.

The result:
- Programmed variety that adds more to the general ambience.
- Only using a single, short, small-size .wav file to generate an effect that might otherwise take several files.

The last part is perhaps the most important. We can now apply this process to more tedious things such as footsteps! Instead of recording 4+ different variations of the same step - bloating the game's size in the process - we can use a single step sound file and apply various effects to it, in-engine, to create variation.

Furthermore, we can even apply separate in-engine effects, depending on the surface (steel, gravel, dirt) or the environment (land, underwater), to change the sound of the step on a whim as long as the categorization structure of different materials or volumes are appropriately set.

This process can help streamline a lot of different parts of the soundscape to work more closely together while taking up less overall space.

### CODE REVIEW

**Comment by wail** [comment]
Very cool. Looking at incorporating MetaSounds was on my mental backlog for the reasons you mention.

**Comment by Absolution2015** [comment]
As I delve deeper into MetaSounds I'll keep leaving such notes with every commit. I'll stick with simple implementations such as this one for a while, trying to use more and more of their features before I move on to more complex systems of sounds.

**Comment by wail** [comment]
Epic's new example project CropOut is using MetaSounds all over, so may be a good resource, although I doubt they are using them to full capability.
At some point I'd like to work through (or for someone else to do so) the current library of OT audio assets to convert to MetaSound.

**Comment by Absolution2015** [comment]
I'll keep in mind taking a look at videos of CropOut (I _really_ doubt I have the space to download it right now), there's definitely a lot of depth to MetaSounds that might be unintuitive to discover through random exploration.

With regards to converting the current OT SoundCues to MetaSounds, it is definitely the right thing to do, and once I have a firm grasp on MetaSounds I can probably get to it, but it would be ideal to first identify _which_ sounds are keepers, and which are temporary. I've stumbled upon several versions of the same weapon, some with different textures, some with different sounds, and it looks like a lil' clean-up might be in order before porting everything to MS. I'm not saying everything _must_ have a 'final sound', but one sound per function (weapon SFX, kill streak announcer voice lines) will ensure we're not turning a small mess into a big mess.

**Pull request closed without merging**
