### PR TITLE
Modify shell master material; add shell textures and materials.

### PR DESCRIPTION
**Pull request by NATOcm**
Adding a basic Wood, Wood plank, Rock, and Concrete wall textures and associated materials based on Content/OpenTournament/Materials/Prototype/Shell_Material_MASTER.

Modified Content/OpenTournament/Materials/Prototype/Shell_Material_MASTER.uasset to allow for toggling normal map, and renamed some variables for clarity.

83513716-91894000-a4d2-11ea-939c-e9a1862680b3
83513728-9817b780-a4d2-11ea-9297-ec16cf5151d2

### CODE REVIEW

**Comment by Saibamen** [comment]
Could you add screenshots?
IMO we need started to work on Pull Request template

**Comment by NATOcm** [comment]
> Could you add screenshots?

Added!

**Comment by Saibamen** [comment]
Tip: You could upload it to prevent deleting files from external hosting

image

image

**Comment by OpenTournament** [comment]
Thanks, this was merged into GitLab & will make it over when we do our next repo update.

**Comment by Saibamen** [comment]
GitLab? There is second repository? Could you update `readme` with link to it?

**Comment by OpenTournament** [comment]
We are working to migrate everything to GitHub

**Pull request closed without merging**
